clone:
  path: github.com/drone-plugins
  recursive: true

build:
  image: armhfbuild/golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=arm
    - CGO_ENABLED=0
  commands:
    - git clone --single-branch https://github.com/drone-plugins/drone-downstream
    - cd drone-downstream
    - sed -i 's/FROM alpine/FROM armhfbuild\/alpine/' Dockerfile
    - go get
    - go build
    - go test

publish:
  docker:
    context: drone-downstream
    file: drone-downstream/Dockerfile
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfplugins/drone-downstream
    when:
      repo: armhf-drone-plugins/drone-downstream
      branch: master

notify:
  gitter:
    webhook: https://webhooks.gitter.im/e/cac16e3f9e62a24bcd78

  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf

plugin:
  name: Trigger
  desc: Trigger builds for downstream repositories
  type: clone
  image: armhfplugins/drone-downstream
  labels:
    - trigger
    - drone
